/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.lucafaggion.thesis.develop.model;

import org.springframework.boot.SpringBootConfiguration;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;

@EnableAutoConfiguration
@SpringBootConfiguration
public class AppIntegrationTestConfiguration {}
