/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.lucafaggion.thesis.test.model;

import org.springframework.boot.SpringBootConfiguration;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

@EnableAutoConfiguration
@SpringBootConfiguration
@EntityScan(basePackages = "com.lucafaggion.thesis.develop")
@EnableJpaRepositories(basePackages = "com.lucafaggion.thesis.develop")
// @ComponentScan(basePackages = { "com.lucafaggion.thesis.develop", "com.lucafaggion.thesis.common.config"})
public class AppIntegrationTestConfiguration {}
