server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://postdb:5432/devdb
    username: postgres
    password: postgres
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always