version: '3.7'
name: thesis-devdb
services:
  postdb:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - thesis-network
    volumes: 
      - thesis-devdb:/var/lib/postgresql/data
  pgAdmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - 9080:80
    networks:
      - thesis-network
    environment:
      - PGADMIN_DEFAULT_EMAIL=luca.faggion@outlook.com
      - PGADMIN_DEFAULT_PASSWORD=postgresmaster
    volumes:
      - pgAdminThesis:/var/lib/pgadmin
  rabbitmq:
    restart: unless-stopped
    image: rabbitmq:3-management
    networks:
      - thesis-network
    ports:
      - "15672:15672"
      - "5672:5672" #Non necessaria siccome sono sulla stessa net

networks:
  thesis-network:
    external: true

volumes:
  thesis-devdb:
    external: true
  pgAdminThesis:
