version: '3.7'
name: thesis-devdb
services:
  postdb:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - thesis-network
    volumes: 
      - thesis-devdb:/var/lib/postgresql/data
  pgAdmin:
    image: dpage/pgadmin4
    ports:
      - 9080:80
    networks:
      - thesis-network
    environment:
      - PGADMIN_DEFAULT_EMAIL=luca.faggion@outlook.com
      - PGADMIN_DEFAULT_PASSWORD=postgresmaster
    volumes:
      - pgAdminThesis:/var/lib/pgadmin

networks:
  thesis-network:
    external: true

volumes:
  thesis-devdb:
    external: true
  pgAdminThesis:
