version: '3.7'
name: thesis-devdb
services:
  #######################################
  #             DATABASE
  #######################################  
  postdb:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - thesis-network
    volumes: 
      - thesis-devdb:/var/lib/postgresql/data
  #######################################
  #          DATABASE TOOl
  #######################################  
  pgAdmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - 9080:80
    networks:
      - thesis-network
    environment:
      - PGADMIN_DEFAULT_EMAIL=luca.faggion@outlook.com
      - PGADMIN_DEFAULT_PASSWORD=postgresmaster
    volumes:
      - pgAdminThesis:/var/lib/pgadmin
  #######################################
  #          MESSAGE BROKER
  #######################################  
  rabbitmq:
    restart: unless-stopped
    image: rabbitmq:3-management
    networks:
      - thesis-network
    ports:
      - "15672:15672"
      - "5672:5672" #Non necessaria siccome sono sulla stessa net
  #######################################
  #          REVERSE PROXY
  #######################################  
  traefik:
    image: traefik:v2.10.4
    container_name: traefik_thesis
    ports:
      - 8880:80
      - 8443:443
      # -- (Optional) Enable Dashboard, don't do in production
      - 1010:8080
    volumes:
      - ./config:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - thesis-network
    # -- (Optional) When using Cloudflare as Cert Resolver
    # environment:
    #   - CF_DNS_API_TOKEN=your-cloudflare-api-token
    # -- (Optional) When using a custom network
    # networks:
    #   - your-traefik-network
    restart: unless-stopped

networks:
  thesis-network:
    external: true

volumes:
  thesis-devdb:
    external: true
  pgAdminThesis:
